In [1]:
# ! cd .. && git pull

In [1]:
%load_ext autoreload
%autoreload 2 

import os

os.chdir('..')

assert os.getcwd()[-14:] == 'lm_commonsense'

In [2]:
from eval import *

In [5]:
ensemble = EnsembleLM()

In [6]:
ensemble.vocab.word_to_char_ids('been')

array([  2,  98, 101, 101, 110,   3,   4,   4,   4,   4,   4,   4,   4,
         4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,
         4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,
         4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4], dtype=int32)

In [7]:
ensemble.question_ids[:5]

[0, 0, 1, 1, 2]

In [65]:
second_question_sentences = ensemble.sentences[4:6]

In [123]:
third_question_sentences = ensemble.sentences[6:8]

In [9]:
ensemble.labels[:8]

[True, False, False, True, True, False, False, True]

In [10]:
ensemble.add_single_model()

Reading cached result from reproduce/lm01/wsc273.probs
Done adding lm01


In [61]:
second_question_probs = ensemble.all_probs[0][4:6]

In [122]:
third_question_probs = ensemble.all_probs[0][6:8]

In [63]:
# 640 - 546

In [62]:
# ensemble.all_probs[0][-94] == ensemble.all_probs[0][-95]

In [57]:
# from utils import cut_to_patches

# ensemble.sentences[:5]

# cut_to_patches(ensemble.sentences[:6], 20, 4)

In [68]:
assert len(second_question_sentences[0]) == len(second_question_sentences[1])
len(second_question_sentences[0])

16

In [124]:
assert len(third_question_sentences[0]) == len(third_question_sentences[1])
len(third_question_sentences[0])

16

In [134]:
first_completion_word_probs = second_question_probs[0, :len(second_question_sentences[0])]
second_completion_word_probs = second_question_probs[1, :len(second_question_sentences[1])]

In [125]:
first_completion_word_probs = third_question_probs[0, :len(third_question_sentences[0])]
second_completion_word_probs = third_question_probs[1, :len(third_question_sentences[1])]

In [116]:
ensemble.question_ids[4:6]

[2, 2]

In [84]:
ensemble.labels[4:6]

[True, False]

In [126]:
ensemble.labels[6:8]

[False, True]

In [135]:
mask = np.zeros(16)
mask[second_question_sentences[0][2:].index('trophy') + 2] = 1

In [136]:
first_completion_partial_word_probs = np.array([max(_) for _ in zip(first_completion_word_probs, mask)])
second_completion_partial_word_probs = np.array([max(_) for _ in zip(second_completion_word_probs, mask)])

In [137]:
first_completion_word_probs

array([8.52542650e-03, 5.38444851e-07, 1.83014272e-04, 9.67347562e-01,
       7.27411301e-04, 7.75002921e-03, 3.01987112e-01, 3.24122317e-04,
       1.44276171e-04, 2.96403741e-04, 6.31977692e-02, 1.31147317e-05,
       2.46247262e-01, 1.41547136e-02, 7.37393722e-02, 5.34790874e-01])

In [138]:
first_completion_partial_word_probs

array([8.52542650e-03, 5.38444851e-07, 1.83014272e-04, 9.67347562e-01,
       7.27411301e-04, 7.75002921e-03, 3.01987112e-01, 3.24122317e-04,
       1.44276171e-04, 2.96403741e-04, 6.31977692e-02, 1.00000000e+00,
       2.46247262e-01, 1.41547136e-02, 7.37393722e-02, 5.34790874e-01])

In [139]:
print(np.prod(first_completion_partial_word_probs, dtype=np.float64))
np.prod(second_completion_partial_word_probs, dtype=np.float64)

1.6658716110079754e-34


2.7517725049936344e-34

In [140]:
print(np.prod(first_completion_word_probs, dtype=np.float64))
np.prod(second_completion_word_probs, dtype=np.float64)

2.1847459226057985e-39


4.265436430758512e-38

In [141]:
first_completion_partial_word_probs / second_completion_partial_word_probs

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.59633723, 0.65897344, 1.50084227,
       1.0264413 ])

In [142]:
(first_completion_partial_word_probs / second_completion_partial_word_probs)[14]

1.5008422696614065

In [143]:
first_completion_word_probs / second_completion_word_probs

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.08460742, 0.59633723, 0.65897344, 1.50084227,
       1.0264413 ])

In [115]:
second_question_sentences[1]

['The',
 'trophy',
 'doesn',
 "'t",
 'fit',
 'into',
 'the',
 'brown',
 'suitcase',
 'because',
 'the',
 'suitcase',
 'is',
 'too',
 'large',
 '.']

In [82]:
second_question_sentences[0]

['The',
 'trophy',
 'doesn',
 "'t",
 'fit',
 'into',
 'the',
 'brown',
 'suitcase',
 'because',
 'the',
 'trophy',
 'is',
 'too',
 'large',
 '.']

In [31]:
np.array(ensemble.question_ids).max()

272

In [40]:
len(ensemble.question_ids)

546

In [39]:
len(ensemble.labels)

546

In [36]:
len(ensemble.sentences)

546

In [35]:
len(ensemble.all_probs[0])

640

In [23]:
import json
questions_json = json.load(open('reproduce/commonsense_test/wsc273.json'))

import pandas as pd
questions_df = pd.DataFrame(questions_json)

In [25]:
questions_df.max()

correctness                                                  True
question_id                                                   272
substitution    When the sponsors of the bill got to the town ...
dtype: object